name: ci
on:
  push:
    branches:
      - demo/**
      - feat/**
      - fix/**

jobs:
  test:
    name: CI 执行流程
    runs-on: ubuntu-latest
    steps:
      - name: 下载 Github 仓库
        uses: actions/checkout@v4

      - name: 下载和安装 Node 环境
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: 安装依赖
        run: npm ci

      - name: 代码校验
        run: npm run lint

      - name: 代码构建
        run: npm run build
